server:
  port: 80

spring:
  freemarker:
    suffix: .ftl
    cache: false
  application:
    name: shiro
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/shrio
    username: root
    password: www1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #data: classpath:tmp-data.sql
    initialization-mode: always
  jpa:
    database: mysql
    showSql: true
    hibernate:
      ddlAuto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true